import { TeacherProfile } from "../types/thumbnail";

// All PW Faculty across Centers:
// - PCMC: Status = "Active" only
// - Viman Nagar: All faculty
// - TC: All faculty
// Subject Order: Physics -> Chemistry -> Mathematics -> Botany -> Zoology -> English -> SST -> General (at last)
export const PW_SHEET_FACULTY_DATABASE: TeacherProfile[] = [
  {
    "id": "pw_teacher_viman_nagar_5_135QmuQq",
    "name": "Bhola Kumar",
    "rawName": "bhola.kumar - PBH",
    "teacherCode": "PBH",
    "subject": "Physics",
    "center": "Viman Nagar",
    "title": "Physics Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/135QmuQqoeFyy8BH05LbNuuRaWnCvnfxy",
    "defaultPosition": "right",
    "driveId": "135QmuQqoeFyy8BH05LbNuuRaWnCvnfxy"
  },
  {
    "id": "pw_teacher_pcmc_54_1kRxMxea",
    "name": "Deepak Kanskar",
    "rawName": "Deepak Kanskar",
    "teacherCode": "PDK",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1kRxMxea0b2AVvIbjIB9cWCHOJjFE7-1A",
    "defaultPosition": "right",
    "driveId": "1kRxMxea0b2AVvIbjIB9cWCHOJjFE7-1A"
  },
  {
    "id": "pw_teacher_viman_nagar_4_1AzIsxDe",
    "name": "Hanuman Sharma",
    "rawName": "hanuman.sharma - PHS",
    "teacherCode": "PHS",
    "subject": "Physics",
    "center": "Viman Nagar",
    "title": "Physics Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1AzIsxDeD3w6yIxkQ0EO7a-BXbwOgLP_y",
    "defaultPosition": "right",
    "driveId": "1AzIsxDeD3w6yIxkQ0EO7a-BXbwOgLP_y"
  },
  {
    "id": "pw_teacher_pcmc_60_1OTNB5KE",
    "name": "Himashu Pandey",
    "rawName": "Himashu pandey",
    "teacherCode": "PHP",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1OTNB5KEOaVOnyT5h7AKfhKDjliR2-gcj",
    "defaultPosition": "right",
    "driveId": "1OTNB5KEOaVOnyT5h7AKfhKDjliR2-gcj"
  },
  {
    "id": "pw_teacher_tc_2_1Gzskqbt",
    "name": "Kailash Chandra Tiwari Pkct",
    "rawName": "Kailash Chandra Tiwari PKCT",
    "teacherCode": "PKCT",
    "subject": "Physics",
    "center": "TC",
    "title": "Physics Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1Gzskqbt2hEcW3w_ov5JBIYQV7f-2iBha",
    "defaultPosition": "right",
    "driveId": "1Gzskqbt2hEcW3w_ov5JBIYQV7f-2iBha"
  },
  {
    "id": "pw_teacher_pcmc_22_1gzUEFms",
    "name": "Krishna Kumar",
    "rawName": "Krishna Kumar",
    "teacherCode": "PKK",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1gzUEFmsnv48QJc1RS1u-CtkqV-LLFodg",
    "defaultPosition": "right",
    "driveId": "1gzUEFmsnv48QJc1RS1u-CtkqV-LLFodg"
  },
  {
    "id": "pw_teacher_pcmc_30_12JhYIu6",
    "name": "Love Swarnkar",
    "rawName": "love.swarnkar",
    "teacherCode": "PLS",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/12JhYIu6XQgU77AoW4rSHDVIkwyFcTs0H",
    "defaultPosition": "right",
    "driveId": "12JhYIu6XQgU77AoW4rSHDVIkwyFcTs0H"
  },
  {
    "id": "pw_teacher_pcmc_68_12jDmU8V",
    "name": "Mayank Tamrakar",
    "rawName": "Mayank Tamrakar",
    "teacherCode": "PMT",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/12jDmU8VPfyjdS60adf8FtbpGfziHXYN7",
    "defaultPosition": "right",
    "driveId": "12jDmU8VPfyjdS60adf8FtbpGfziHXYN7"
  },
  {
    "id": "pw_teacher_pcmc_77_10Ct9EFo",
    "name": "Mayur Dhawale",
    "rawName": "Mayur Dhawale",
    "teacherCode": "PMD",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/10Ct9EFoacap5PQ6e39zYZ-R6xFdUJo6Y",
    "defaultPosition": "right",
    "driveId": "10Ct9EFoacap5PQ6e39zYZ-R6xFdUJo6Y"
  },
  {
    "id": "pw_teacher_viman_nagar_13_1xzX0R04",
    "name": "Naveen Kumar",
    "rawName": "naveen.kumar - PNK",
    "teacherCode": "PNK",
    "subject": "Physics",
    "center": "Viman Nagar",
    "title": "Physics Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1xzX0R047VI9Ks-JRmQEeJUsDqQXl-97Y",
    "defaultPosition": "right",
    "driveId": "1xzX0R047VI9Ks-JRmQEeJUsDqQXl-97Y"
  },
  {
    "id": "pw_teacher_pcmc_65_14emuxr0",
    "name": "Quaneet Laraib",
    "rawName": "quaneet laraib",
    "teacherCode": "PQL",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/14emuxr0So1EJ46K03Y-WNBq12JdV8RZy",
    "defaultPosition": "right",
    "driveId": "14emuxr0So1EJ46K03Y-WNBq12JdV8RZy"
  },
  {
    "id": "pw_teacher_tc_7_1VAtgiD2",
    "name": "Ritesh Kumar PRK",
    "rawName": "Ritesh Kumar PRK",
    "teacherCode": "PRK",
    "subject": "Physics",
    "center": "TC",
    "title": "Physics Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1VAtgiD2uR106aDKNwN8nKHVO9RiXABh8",
    "defaultPosition": "right",
    "driveId": "1VAtgiD2uR106aDKNwN8nKHVO9RiXABh8"
  },
  {
    "id": "pw_teacher_pcmc_42_1wwkeG08",
    "name": "Sachin Kumar Singh",
    "rawName": "Sachin Kumar Singh",
    "teacherCode": "PSK",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1wwkeG08zOMD-tcJFETgUGbV9brb1Sakl",
    "defaultPosition": "right",
    "driveId": "1wwkeG08zOMD-tcJFETgUGbV9brb1Sakl"
  },
  {
    "id": "pw_teacher_pcmc_14_1OAjfd6w",
    "name": "Surabhi Gupta",
    "rawName": "surabhi.gupta",
    "teacherCode": "PSG",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1OAjfd6w2VFzLpk3mYXj525yChBa_R9DN",
    "defaultPosition": "right",
    "driveId": "1OAjfd6w2VFzLpk3mYXj525yChBa_R9DN"
  },
  {
    "id": "pw_teacher_pcmc_7_1OAjfd6w",
    "name": "Surbhi Gupta",
    "rawName": "Surbhi Gupta",
    "teacherCode": "PSG",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1OAjfd6w2VFzLpk3mYXj525yChBa_R9DN",
    "defaultPosition": "right",
    "driveId": "1OAjfd6w2VFzLpk3mYXj525yChBa_R9DN"
  },
  {
    "id": "pw_teacher_pcmc_44_1NQWc89K",
    "name": "Surendra Bijarnia",
    "rawName": "Surendra Bijarnia",
    "teacherCode": "PSB",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1NQWc89KsWxATzQarrtDqfLQk-qLgYcuQ",
    "defaultPosition": "right",
    "driveId": "1NQWc89KsWxATzQarrtDqfLQk-qLgYcuQ"
  },
  {
    "id": "pw_teacher_viman_nagar_2_13VVoqgH",
    "name": "Tushar Saini1",
    "rawName": "tushar.saini1 - PTS",
    "teacherCode": "PTS",
    "subject": "Physics",
    "center": "Viman Nagar",
    "title": "Physics Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/13VVoqgH2pg_fOENZouYRZC_ZHfntIM8R",
    "defaultPosition": "right",
    "driveId": "13VVoqgH2pg_fOENZouYRZC_ZHfntIM8R"
  },
  {
    "id": "pw_teacher_pcmc_78_1kQHciQC",
    "name": "Zeeshan Eqbal",
    "rawName": "Zeeshan Eqbal",
    "teacherCode": "PZE",
    "subject": "Physics",
    "center": "PCMC",
    "title": "Physics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1kQHciQCdwA0cEiC0WF9TWNcVAPcp65QP",
    "defaultPosition": "right",
    "driveId": "1kQHciQCdwA0cEiC0WF9TWNcVAPcp65QP"
  },
  {
    "id": "pw_teacher_tc_8_1kVEsW17",
    "name": "Aniket Mishra Sir CAM",
    "rawName": "Aniket Mishra sir CAM",
    "teacherCode": "CAM",
    "subject": "Chemistry",
    "center": "TC",
    "title": "Chemistry Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1kVEsW17jY2a1erH4nW3tYehcWQaR9UEo",
    "defaultPosition": "right",
    "driveId": "1kVEsW17jY2a1erH4nW3tYehcWQaR9UEo"
  },
  {
    "id": "pw_teacher_pcmc_64_157UoEHk",
    "name": "Arshad Ansari",
    "rawName": "Arshad Ansari",
    "teacherCode": "CAA",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/157UoEHkH2snKOGIWNg5Qyz2Sm0hOrK98",
    "defaultPosition": "right",
    "driveId": "157UoEHkH2snKOGIWNg5Qyz2Sm0hOrK98"
  },
  {
    "id": "pw_teacher_viman_nagar_7_1ZeSRMlp",
    "name": "Bhawna Sharma",
    "rawName": "bhawna.sharma - CBS",
    "teacherCode": "CBS",
    "subject": "Chemistry",
    "center": "Viman Nagar",
    "title": "Chemistry Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1ZeSRMlpyM_J6DdtOzIlSGVTnl6z7dIBv",
    "defaultPosition": "right",
    "driveId": "1ZeSRMlpyM_J6DdtOzIlSGVTnl6z7dIBv"
  },
  {
    "id": "pw_teacher_pcmc_50_1qsnD_AO",
    "name": "Govind Singh Shekhawat",
    "rawName": "Govind Singh Shekhawat",
    "teacherCode": "CGS",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1qsnD_AOoLskVo7h_BDDena9xZvHdxKoe",
    "defaultPosition": "right",
    "driveId": "1qsnD_AOoLskVo7h_BDDena9xZvHdxKoe"
  },
  {
    "id": "pw_teacher_viman_nagar_8_1AWrPq3L",
    "name": "Gurujeet Kumar",
    "rawName": "gurujeet.kumar - CGK",
    "teacherCode": "CGK",
    "subject": "Chemistry",
    "center": "Viman Nagar",
    "title": "Chemistry Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1AWrPq3LfFHg34CWgRYzzuoopzHIvKGlH",
    "defaultPosition": "right",
    "driveId": "1AWrPq3LfFHg34CWgRYzzuoopzHIvKGlH"
  },
  {
    "id": "pw_teacher_viman_nagar_3_1rGQVUcf",
    "name": "Hansraj Prajapat",
    "rawName": "hansraj.prajapat - CHP",
    "teacherCode": "CHP",
    "subject": "Chemistry",
    "center": "Viman Nagar",
    "title": "Chemistry Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1rGQVUcfKn9Ge9tcY8yrh-1Bt-0BqINnS",
    "defaultPosition": "right",
    "driveId": "1rGQVUcfKn9Ge9tcY8yrh-1Bt-0BqINnS"
  },
  {
    "id": "pw_teacher_pcmc_35_18a8mFnv",
    "name": "Kunal Verma",
    "rawName": "Kunal Verma",
    "teacherCode": "CKV",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/18a8mFnvvlMlGct0CIGWjLpFmKGAbxkdM",
    "defaultPosition": "right",
    "driveId": "18a8mFnvvlMlGct0CIGWjLpFmKGAbxkdM"
  },
  {
    "id": "pw_teacher_viman_nagar_11_1eywhPDC",
    "name": "Mahender Pal",
    "rawName": "mahender.pal - CMP",
    "teacherCode": "CMP",
    "subject": "Chemistry",
    "center": "Viman Nagar",
    "title": "Chemistry Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1eywhPDCV5c-OYO5HMuciy9rlXYqzmt9N",
    "defaultPosition": "right",
    "driveId": "1eywhPDCV5c-OYO5HMuciy9rlXYqzmt9N"
  },
  {
    "id": "pw_teacher_pcmc_59_14wXAGyY",
    "name": "Mohd Shazil Iqbal",
    "rawName": "Mohd Shazil Iqbal",
    "teacherCode": "CSI",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/14wXAGyYifdfR8SWG79ktGSpJIgZfkRkD",
    "defaultPosition": "right",
    "driveId": "14wXAGyYifdfR8SWG79ktGSpJIgZfkRkD"
  },
  {
    "id": "pw_teacher_pcmc_76_14U3hwKp",
    "name": "Nitesh Sir Pcmc",
    "rawName": "Nitesh Sir PCMC",
    "teacherCode": "CNI",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/14U3hwKpbIvkcnHEH2KGtxLpq2VVE8RN7",
    "defaultPosition": "right",
    "driveId": "14U3hwKpbIvkcnHEH2KGtxLpq2VVE8RN7"
  },
  {
    "id": "pw_teacher_pcmc_57_1KlbLdSP",
    "name": "Prajakt Rane",
    "rawName": "Prajakt Rane",
    "teacherCode": "CPR",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1KlbLdSP4I4wh-7XIdWsB9l2iYImcAnuc",
    "defaultPosition": "right",
    "driveId": "1KlbLdSP4I4wh-7XIdWsB9l2iYImcAnuc"
  },
  {
    "id": "pw_teacher_pcmc_1_1ZVW2Y7O",
    "name": "Rishesh Ameriya CRA",
    "rawName": "Rishesh Ameriya CRA",
    "teacherCode": "CRA",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1ZVW2Y7O_9q0bx4ctucKd5p6n00_b47Sk",
    "defaultPosition": "right",
    "driveId": "1ZVW2Y7O_9q0bx4ctucKd5p6n00_b47Sk"
  },
  {
    "id": "pw_teacher_tc_4_1VFswxTn",
    "name": "Sadika Siddiqui Cssm",
    "rawName": "Sadika siddiqui CSSM",
    "teacherCode": "CSSM",
    "subject": "Chemistry",
    "center": "TC",
    "title": "Chemistry Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1VFswxTnFZTVwovbgKOvBzjkX-2g_Ip_J",
    "defaultPosition": "right",
    "driveId": "1VFswxTnFZTVwovbgKOvBzjkX-2g_Ip_J"
  },
  {
    "id": "pw_teacher_pcmc_46_1Jxlw1R9",
    "name": "Shivani Kalra",
    "rawName": "Shivani Kalra",
    "teacherCode": "CSK",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1Jxlw1R9bf6GYMSjgYf--9rKzSTUoJJwG",
    "defaultPosition": "right",
    "driveId": "1Jxlw1R9bf6GYMSjgYf--9rKzSTUoJJwG"
  },
  {
    "id": "pw_teacher_pcmc_56_1oEurHUP",
    "name": "Sunil Singh",
    "rawName": "Sunil singh",
    "teacherCode": "CSS",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1oEurHUPDlb2AmsXxmTfW80HVMRp4FXZR",
    "defaultPosition": "right",
    "driveId": "1oEurHUPDlb2AmsXxmTfW80HVMRp4FXZR"
  },
  {
    "id": "pw_teacher_pcmc_75_14ujOkns",
    "name": "Tanveer Hasan",
    "rawName": "Tanveer Hasan",
    "teacherCode": "CTH",
    "subject": "Chemistry",
    "center": "PCMC",
    "title": "Chemistry Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/14ujOkns4CXNkeZe7AKLbRQM_ZxrPPXmV",
    "defaultPosition": "right",
    "driveId": "14ujOkns4CXNkeZe7AKLbRQM_ZxrPPXmV"
  },
  {
    "id": "pw_teacher_pcmc_45_1X-udRyY",
    "name": "Ajay Patidar",
    "rawName": "AJAY PATIDAR",
    "teacherCode": "MAP",
    "subject": "Mathematics",
    "center": "PCMC",
    "title": "Mathematics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1X-udRyYDXnnVMe2vcW3W4xpg4f8vOYim",
    "defaultPosition": "right",
    "driveId": "1X-udRyYDXnnVMe2vcW3W4xpg4f8vOYim"
  },
  {
    "id": "pw_teacher_tc_1_1xFx_w8f",
    "name": "Balraj Singh MBS",
    "rawName": "Balraj Singh MBS",
    "teacherCode": "MBS",
    "subject": "Mathematics",
    "center": "TC",
    "title": "Mathematics Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1xFx_w8fgs2eBbSD1Bbk8L5EkKpcpAtrM",
    "defaultPosition": "right",
    "driveId": "1xFx_w8fgs2eBbSD1Bbk8L5EkKpcpAtrM"
  },
  {
    "id": "pw_teacher_viman_nagar_10_1IoOabu1",
    "name": "Danish Hashmi",
    "rawName": "danish.hashmi - MDH",
    "teacherCode": "MDH",
    "subject": "Mathematics",
    "center": "Viman Nagar",
    "title": "Mathematics Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1IoOabu1Sjwl44IAN33foW0Aqj_ai8jZi",
    "defaultPosition": "right",
    "driveId": "1IoOabu1Sjwl44IAN33foW0Aqj_ai8jZi"
  },
  {
    "id": "pw_teacher_pcmc_37_1nnsyGh5",
    "name": "Imran Ahmad",
    "rawName": "imran.ahmad",
    "teacherCode": "MIA",
    "subject": "Mathematics",
    "center": "PCMC",
    "title": "Mathematics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1nnsyGh5TNT9bvT2DyyjlHHluronWxNEf",
    "defaultPosition": "right",
    "driveId": "1nnsyGh5TNT9bvT2DyyjlHHluronWxNEf"
  },
  {
    "id": "pw_teacher_pcmc_49_1xfg1_IS",
    "name": "Kuldeep Dewangan Sir",
    "rawName": "Kuldeep Dewangan sir",
    "teacherCode": "MKD",
    "subject": "Mathematics",
    "center": "PCMC",
    "title": "Mathematics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1xfg1_ISDpl04EYpOHwkNlIM3uqmx6bx0",
    "defaultPosition": "right",
    "driveId": "1xfg1_ISDpl04EYpOHwkNlIM3uqmx6bx0"
  },
  {
    "id": "pw_teacher_pcmc_74_1YhRErXV",
    "name": "Mohit Sharma",
    "rawName": "Mohit Sharma",
    "teacherCode": "MMS",
    "subject": "Mathematics",
    "center": "PCMC",
    "title": "Mathematics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1YhRErXVBRwotYOZM6et9FdsHucnUVYHr",
    "defaultPosition": "right",
    "driveId": "1YhRErXVBRwotYOZM6et9FdsHucnUVYHr"
  },
  {
    "id": "pw_teacher_pcmc_69_1lEu0oRw",
    "name": "Mukesh Sir Pcmc",
    "rawName": "Mukesh Sir PCMC",
    "teacherCode": "MMK",
    "subject": "Mathematics",
    "center": "PCMC",
    "title": "Mathematics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1lEu0oRw-mhadse8SyPlAJ_HIoLe9BXXz",
    "defaultPosition": "right",
    "driveId": "1lEu0oRw-mhadse8SyPlAJ_HIoLe9BXXz"
  },
  {
    "id": "pw_teacher_pcmc_66_1vo8dAr8",
    "name": "Prashant Mishra",
    "rawName": "Prashant Mishra",
    "teacherCode": "MPH",
    "subject": "Mathematics",
    "center": "PCMC",
    "title": "Mathematics Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1vo8dAr8CD1Pjxvvfg3gsmBmt8hD7OzFl",
    "defaultPosition": "right",
    "driveId": "1vo8dAr8CD1Pjxvvfg3gsmBmt8hD7OzFl"
  },
  {
    "id": "pw_teacher_viman_nagar_30_1HsCYDEI",
    "name": "Rahul Meena MRM",
    "rawName": "Rahul Meena MRM",
    "teacherCode": "MRM",
    "subject": "Mathematics",
    "center": "Viman Nagar",
    "title": "Mathematics Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1HsCYDEIwQpEzSoLEMJMTordEFA6_1Cr9",
    "defaultPosition": "right",
    "driveId": "1HsCYDEIwQpEzSoLEMJMTordEFA6_1Cr9"
  },
  {
    "id": "pw_teacher_viman_nagar_14_1kMtN-yN",
    "name": "Rohini Thete",
    "rawName": "rohini.thete - MRT",
    "teacherCode": "MRT",
    "subject": "Mathematics",
    "center": "Viman Nagar",
    "title": "Mathematics Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1kMtN-yNuNNQe6hxZLYgyBrUh4CydK781",
    "defaultPosition": "right",
    "driveId": "1kMtN-yNuNNQe6hxZLYgyBrUh4CydK781"
  },
  {
    "id": "pw_teacher_viman_nagar_6_1ijlKFE_",
    "name": "Siddharth Sharma2",
    "rawName": "siddharth.sharma2 - MSS",
    "teacherCode": "MSS",
    "subject": "Mathematics",
    "center": "Viman Nagar",
    "title": "Mathematics Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1ijlKFE_2eGOetq2qSiI2f7Oi007D_QbQ",
    "defaultPosition": "right",
    "driveId": "1ijlKFE_2eGOetq2qSiI2f7Oi007D_QbQ"
  },
  {
    "id": "pw_teacher_tc_9_1l4Xsank",
    "name": "Vikas Kumar Mvks",
    "rawName": "Vikas Kumar MVKS",
    "teacherCode": "MVKS",
    "subject": "Mathematics",
    "center": "TC",
    "title": "Mathematics Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1l4XsankeSxeZcprujEEPXSMw3QkXli1G",
    "defaultPosition": "right",
    "driveId": "1l4XsankeSxeZcprujEEPXSMw3QkXli1G"
  },
  {
    "id": "pw_teacher_pcmc_70_1wUDcxl2",
    "name": "Alok Kumar Shukla",
    "rawName": "Alok Kumar Shukla",
    "teacherCode": "BAK",
    "subject": "Botany",
    "center": "PCMC",
    "title": "Botany Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1wUDcxl2fiyDJN2dgFIdZ7FCGya7wPDxi",
    "defaultPosition": "right",
    "driveId": "1wUDcxl2fiyDJN2dgFIdZ7FCGya7wPDxi"
  },
  {
    "id": "pw_teacher_tc_3_1rJCqIQ0",
    "name": "Dimple Data BDD",
    "rawName": "Dimple Data BDD",
    "teacherCode": "BDD",
    "subject": "Botany",
    "center": "TC",
    "title": "Botany Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1rJCqIQ08oqX23813w7A43JeDQ4ChCZtX",
    "defaultPosition": "right",
    "driveId": "1rJCqIQ08oqX23813w7A43JeDQ4ChCZtX"
  },
  {
    "id": "pw_teacher_tc_11_1yuStE4J",
    "name": "Ehsan Alam Beas",
    "rawName": "Ehsan Alam BEAS",
    "teacherCode": "BEAS",
    "subject": "Botany",
    "center": "TC",
    "title": "Botany Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1yuStE4Jij8VjQkfIk52ZbQFhcJRdPYUx",
    "defaultPosition": "right",
    "driveId": "1yuStE4Jij8VjQkfIk52ZbQFhcJRdPYUx"
  },
  {
    "id": "pw_teacher_viman_nagar_1_10QrCIdO",
    "name": "Girish Prajapat",
    "rawName": "girish.prajapat - BGP",
    "teacherCode": "BGP",
    "subject": "Botany",
    "center": "Viman Nagar",
    "title": "Botany Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/10QrCIdO1Nvj59UzoSXxrTCa1MSFfu5fh",
    "defaultPosition": "right",
    "driveId": "10QrCIdO1Nvj59UzoSXxrTCa1MSFfu5fh"
  },
  {
    "id": "pw_teacher_pcmc_36_1fdrN-rF",
    "name": "Kamlesh Ranjan",
    "rawName": "kamlesh ranjan",
    "teacherCode": "BKR",
    "subject": "Botany",
    "center": "PCMC",
    "title": "Botany Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1fdrN-rFdV3E0mNHgXdmyMVSZI3z-rQpO",
    "defaultPosition": "right",
    "driveId": "1fdrN-rFdV3E0mNHgXdmyMVSZI3z-rQpO"
  },
  {
    "id": "pw_teacher_pcmc_72_1ODCttyS",
    "name": "Mukul Rohilla",
    "rawName": "Mukul Rohilla",
    "teacherCode": "BMR",
    "subject": "Botany",
    "center": "PCMC",
    "title": "Botany Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1ODCttySzkcWtOUx6Y3i56JdD-eAZYGZl",
    "defaultPosition": "right",
    "driveId": "1ODCttySzkcWtOUx6Y3i56JdD-eAZYGZl"
  },
  {
    "id": "pw_teacher_viman_nagar_9_18MRMCBH",
    "name": "Seema Manwani",
    "rawName": "seema.manwani - BSM",
    "teacherCode": "BSM",
    "subject": "Botany",
    "center": "Viman Nagar",
    "title": "Botany Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/18MRMCBHRO0OJLEZCJOWsjEg_rkVlJlvW",
    "defaultPosition": "right",
    "driveId": "18MRMCBHRO0OJLEZCJOWsjEg_rkVlJlvW"
  },
  {
    "id": "pw_teacher_tc_10_1urDM1RB",
    "name": "Jaspreet Kaur ZJK",
    "rawName": "Jaspreet kaur ZJK",
    "teacherCode": "ZJK",
    "subject": "Zoology",
    "center": "TC",
    "title": "Zoology Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1urDM1RB7J37Z9PnuJcmA0JG_XDHiCUJ6",
    "defaultPosition": "right",
    "driveId": "1urDM1RB7J37Z9PnuJcmA0JG_XDHiCUJ6"
  },
  {
    "id": "pw_teacher_viman_nagar_12_1QSwF9IT",
    "name": "Naina Chawla",
    "rawName": "naina.chawla - ZNC",
    "teacherCode": "ZNC",
    "subject": "Zoology",
    "center": "Viman Nagar",
    "title": "Zoology Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1QSwF9ITCGYs6SH77RFSYm8KPO9oHsTHf",
    "defaultPosition": "right",
    "driveId": "1QSwF9ITCGYs6SH77RFSYm8KPO9oHsTHf"
  },
  {
    "id": "pw_teacher_pcmc_13_1JMGprjI",
    "name": "Shashank Nagar",
    "rawName": "shashank.nagar",
    "teacherCode": "ZSN",
    "subject": "Zoology",
    "center": "PCMC",
    "title": "Zoology Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1JMGprjImJtSSq3eokNxjyuuHZGNUBXxf",
    "defaultPosition": "right",
    "driveId": "1JMGprjImJtSSq3eokNxjyuuHZGNUBXxf"
  },
  {
    "id": "pw_teacher_pcmc_58_17ZYzC5X",
    "name": "Shreya Ma'am",
    "rawName": "Shreya Ma'am",
    "teacherCode": "ZSS",
    "subject": "Zoology",
    "center": "PCMC",
    "title": "Zoology Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/17ZYzC5XwNsULKganKUfOghpgG6JIgtWM",
    "defaultPosition": "right",
    "driveId": "17ZYzC5XwNsULKganKUfOghpgG6JIgtWM"
  },
  {
    "id": "pw_teacher_pcmc_8_1kl-lPiE",
    "name": "Shweta Vasoya",
    "rawName": "Shweta Vasoya",
    "teacherCode": "ZSV",
    "subject": "Zoology",
    "center": "PCMC",
    "title": "Zoology Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1kl-lPiE_8EW50EAQ4s_S6eiipXDxp0go",
    "defaultPosition": "right",
    "driveId": "1kl-lPiE_8EW50EAQ4s_S6eiipXDxp0go"
  },
  {
    "id": "pw_teacher_pcmc_55_1Exd3R4k",
    "name": "Ishfaq Ahmad Dar",
    "rawName": "Ishfaq Ahmad Dar",
    "teacherCode": "EID",
    "subject": "English",
    "center": "PCMC",
    "title": "English Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1Exd3R4k6MDx1WOgdILeserjJNQ_pNmjp",
    "defaultPosition": "right",
    "driveId": "1Exd3R4k6MDx1WOgdILeserjJNQ_pNmjp"
  },
  {
    "id": "pw_teacher_tc_6_1zEXuQai",
    "name": "Priti Tiwari Mam Epts",
    "rawName": "Priti Tiwari Mam EPTS",
    "teacherCode": "EPTS",
    "subject": "English",
    "center": "TC",
    "title": "English Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1zEXuQaiGWl_VtC23na7yIuonjPKQOUhU",
    "defaultPosition": "right",
    "driveId": "1zEXuQaiGWl_VtC23na7yIuonjPKQOUhU"
  },
  {
    "id": "pw_teacher_pcmc_61_11dFlJEu",
    "name": "Anurag Atul",
    "rawName": "Anurag Atul",
    "teacherCode": "SAA",
    "subject": "SST",
    "center": "PCMC",
    "title": "SST Faculty | PCMC",
    "imageUrl": "https://lh3.googleusercontent.com/d/11dFlJEuyXLOhhfpUrQbwjt31OHJOo-7N",
    "defaultPosition": "right",
    "driveId": "11dFlJEuyXLOhhfpUrQbwjt31OHJOo-7N"
  },
  {
    "id": "pw_teacher_viman_nagar_36_1dGi4Knb",
    "name": "Mohit Yadav SMY",
    "rawName": "Mohit Yadav SMY",
    "teacherCode": "SMY",
    "subject": "SST",
    "center": "Viman Nagar",
    "title": "SST Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1dGi4KnbNW8koQT2lOsT0nUYkesdA-6Z5",
    "defaultPosition": "right",
    "driveId": "1dGi4KnbNW8koQT2lOsT0nUYkesdA-6Z5"
  },
  {
    "id": "pw_teacher_viman_nagar_15_1dGi4Knb",
    "name": "Mohit Yadav1",
    "rawName": "mohit.yadav1 - SMY",
    "teacherCode": "SMY",
    "subject": "SST",
    "center": "Viman Nagar",
    "title": "SST Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1dGi4KnbNW8koQT2lOsT0nUYkesdA-6Z5",
    "defaultPosition": "right",
    "driveId": "1dGi4KnbNW8koQT2lOsT0nUYkesdA-6Z5"
  },
  {
    "id": "pw_teacher_tc_5_17lyhIIW",
    "name": "Supanjita Mam Svsm",
    "rawName": "Supanjita mam SVSM",
    "teacherCode": "SVSM",
    "subject": "SST",
    "center": "TC",
    "title": "SST Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/17lyhIIWd2juE8aoy8HktFmu41YRfw77D",
    "defaultPosition": "right",
    "driveId": "17lyhIIWd2juE8aoy8HktFmu41YRfw77D"
  },
  {
    "id": "pw_teacher_viman_nagar_23_1NRR5qgY",
    "name": "Aasiya Maam",
    "rawName": "Aasiya maam",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1NRR5qgY6M5WFJ9pgVJuaGJVopQyIu0WP",
    "defaultPosition": "right",
    "driveId": "1NRR5qgY6M5WFJ9pgVJuaGJVopQyIu0WP"
  },
  {
    "id": "pw_teacher_viman_nagar_38_1FJMxDgb",
    "name": "Abhay Pratap Singh",
    "rawName": "Abhay Pratap Singh",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1FJMxDgbB5QnH0a8mkoypRGCRPGx8aWtf",
    "defaultPosition": "right",
    "driveId": "1FJMxDgbB5QnH0a8mkoypRGCRPGx8aWtf"
  },
  {
    "id": "pw_teacher_viman_nagar_17_15Z2oZkI",
    "name": "Abhijeet Sir",
    "rawName": "Abhijeet sir",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/15Z2oZkIyd1x9LYyBNkcyTwglD857-ghV",
    "defaultPosition": "right",
    "driveId": "15Z2oZkIyd1x9LYyBNkcyTwglD857-ghV"
  },
  {
    "id": "pw_teacher_viman_nagar_33_1e87ZYLY",
    "name": "Ambadas Sir",
    "rawName": "Ambadas Sir",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1e87ZYLYb2AeLMHxm9Ewm4PBj29pZe7-u",
    "defaultPosition": "right",
    "driveId": "1e87ZYLYb2AeLMHxm9Ewm4PBj29pZe7-u"
  },
  {
    "id": "pw_teacher_viman_nagar_25_1GP8dS7L",
    "name": "Anshul Sir",
    "rawName": "Anshul Sir",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1GP8dS7LPno0kKx_IoLwzInhcDyju3dL6",
    "defaultPosition": "right",
    "driveId": "1GP8dS7LPno0kKx_IoLwzInhcDyju3dL6"
  },
  {
    "id": "pw_teacher_tc_19_1-OFdG0Q",
    "name": "Anup Kumar Vimal",
    "rawName": "Anup kumar vimal",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1-OFdG0QjVD6WXoPIV2FJCzC5TM-GS71W",
    "defaultPosition": "right",
    "driveId": "1-OFdG0QjVD6WXoPIV2FJCzC5TM-GS71W"
  },
  {
    "id": "pw_teacher_tc_21_1eAF0RtB",
    "name": "Arif Sir",
    "rawName": "Arif Sir",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1eAF0RtBctjf1k-t8WTBEGR_pSSJC0wiK",
    "defaultPosition": "right",
    "driveId": "1eAF0RtBctjf1k-t8WTBEGR_pSSJC0wiK"
  },
  {
    "id": "pw_teacher_viman_nagar_26_1-uGndpb",
    "name": "Arvind Kumar",
    "rawName": "Arvind kumar",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1-uGndpb6KQcEo1a4HsSUQCGRlwfyPDEd",
    "defaultPosition": "right",
    "driveId": "1-uGndpb6KQcEo1a4HsSUQCGRlwfyPDEd"
  },
  {
    "id": "pw_teacher_viman_nagar_20_1DyfAN1Q",
    "name": "Bhawani Maam",
    "rawName": "Bhawani maam.",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1DyfAN1QIQp3ofeo1pgxgQCPadWPr4RSK",
    "defaultPosition": "right",
    "driveId": "1DyfAN1QIQp3ofeo1pgxgQCPadWPr4RSK"
  },
  {
    "id": "pw_teacher_viman_nagar_24_1VElSonb",
    "name": "Harshit Sir",
    "rawName": "Harshit Sir",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1VElSonbuK4R_Nc45WoCVfFkV7NFFgcNM",
    "defaultPosition": "right",
    "driveId": "1VElSonbuK4R_Nc45WoCVfFkV7NFFgcNM"
  },
  {
    "id": "pw_teacher_viman_nagar_40_1_tkTvP1",
    "name": "Janardan Dixit",
    "rawName": "janardan dixit",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1_tkTvP1Luffzxdgwzq4r89AH5QhKSkpV",
    "defaultPosition": "right",
    "driveId": "1_tkTvP1Luffzxdgwzq4r89AH5QhKSkpV"
  },
  {
    "id": "pw_teacher_viman_nagar_41_1i7AChwA",
    "name": "Kalyani Diwate",
    "rawName": "Kalyani Diwate",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1i7AChwALiozo7MgRUSbBQ8LGBdzBhiwK",
    "defaultPosition": "right",
    "driveId": "1i7AChwALiozo7MgRUSbBQ8LGBdzBhiwK"
  },
  {
    "id": "pw_teacher_tc_18_1fdrN-rF",
    "name": "Kamlesh Ranjan",
    "rawName": "kamlesh ranjan",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1fdrN-rFdV3E0mNHgXdmyMVSZI3z-rQpO",
    "defaultPosition": "right",
    "driveId": "1fdrN-rFdV3E0mNHgXdmyMVSZI3z-rQpO"
  },
  {
    "id": "pw_teacher_tc_14_1Y1d7-Az",
    "name": "Mazul_sir",
    "rawName": "Mazul_sir_TC",
    "teacherCode": "TC",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1Y1d7-AzHlMWdIku7OHj5j33_vcQXHxZG",
    "defaultPosition": "right",
    "driveId": "1Y1d7-AzHlMWdIku7OHj5j33_vcQXHxZG"
  },
  {
    "id": "pw_teacher_tc_12_15FpE40b",
    "name": "Monica Maam",
    "rawName": "Monica Maam",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/15FpE40bYHoM0Yj7uJ7Ub7BZJ9hirIcRL",
    "defaultPosition": "right",
    "driveId": "15FpE40bYHoM0Yj7uJ7Ub7BZJ9hirIcRL"
  },
  {
    "id": "pw_teacher_tc_22_1ODCttyS",
    "name": "Mukul Rohilla",
    "rawName": "Mukul Rohilla",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1ODCttySzkcWtOUx6Y3i56JdD-eAZYGZl",
    "defaultPosition": "right",
    "driveId": "1ODCttySzkcWtOUx6Y3i56JdD-eAZYGZl"
  },
  {
    "id": "pw_teacher_viman_nagar_32_1Z31C1Aa",
    "name": "Nawlesh Sir",
    "rawName": "Nawlesh Sir",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1Z31C1AaII8V9B6GSjH5DFqD1_tJKTkJx",
    "defaultPosition": "right",
    "driveId": "1Z31C1AaII8V9B6GSjH5DFqD1_tJKTkJx"
  },
  {
    "id": "pw_teacher_tc_13_1CAKNTcj",
    "name": "Neeraj Sir TC",
    "rawName": "Neeraj Sir TC",
    "teacherCode": "TC",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1CAKNTcjtQxx7PE9VyMZEj_VotUXdBHmX",
    "defaultPosition": "right",
    "driveId": "1CAKNTcjtQxx7PE9VyMZEj_VotUXdBHmX"
  },
  {
    "id": "pw_teacher_viman_nagar_43_1tsInd5T",
    "name": "Neha Verma",
    "rawName": "Neha verma",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1tsInd5TAWj9HB2scuhjiik-vT-lfePXU",
    "defaultPosition": "right",
    "driveId": "1tsInd5TAWj9HB2scuhjiik-vT-lfePXU"
  },
  {
    "id": "pw_teacher_viman_nagar_21_1cZivJa7",
    "name": "Nikhil Kumar",
    "rawName": "nikhil.kumar",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1cZivJa740dFtG2mZa5shxDfttp3UDXJu",
    "defaultPosition": "right",
    "driveId": "1cZivJa740dFtG2mZa5shxDfttp3UDXJu"
  },
  {
    "id": "pw_teacher_viman_nagar_37_1cGXCTDP",
    "name": "Nurjanat Khatun",
    "rawName": "Nurjanat Khatun",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1cGXCTDPE6BGy3U5_dVmWdAotOaYJdRM1",
    "defaultPosition": "right",
    "driveId": "1cGXCTDPE6BGy3U5_dVmWdAotOaYJdRM1"
  },
  {
    "id": "pw_teacher_viman_nagar_39_1QjNMtn0",
    "name": "Parth Kulkarni",
    "rawName": "Parth Kulkarni",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1QjNMtn0rOJkrixlNOJKfkRi7j6AiJWxT",
    "defaultPosition": "right",
    "driveId": "1QjNMtn0rOJkrixlNOJKfkRi7j6AiJWxT"
  },
  {
    "id": "pw_teacher_tc_20_1gJTtJ15",
    "name": "Prachi Chaudhary",
    "rawName": "Prachi.chaudhary",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1gJTtJ15xpkLm2Urjls9VgEHLc_0DMcGs",
    "defaultPosition": "right",
    "driveId": "1gJTtJ15xpkLm2Urjls9VgEHLc_0DMcGs"
  },
  {
    "id": "pw_teacher_viman_nagar_35_1TMhO4h9",
    "name": "Pratim Das",
    "rawName": "pratim das",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1TMhO4h94siiaR87yy_EhfGToXap7O-HS",
    "defaultPosition": "right",
    "driveId": "1TMhO4h94siiaR87yy_EhfGToXap7O-HS"
  },
  {
    "id": "pw_teacher_viman_nagar_27_18qT_z__",
    "name": "Pravin Tripathi (viman Nagar)",
    "rawName": "Pravin tripathi (Viman Nagar)",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/18qT_z__FZ6nm5qM7TjFl7VaEkSwxNWod",
    "defaultPosition": "right",
    "driveId": "18qT_z__FZ6nm5qM7TjFl7VaEkSwxNWod"
  },
  {
    "id": "pw_teacher_viman_nagar_31_1yLjY95d",
    "name": "Ravi Kumar Gupta",
    "rawName": "Ravi Kumar Gupta",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1yLjY95dSayS-St4Otl4A4wpqf4w0W7hP",
    "defaultPosition": "right",
    "driveId": "1yLjY95dSayS-St4Otl4A4wpqf4w0W7hP"
  },
  {
    "id": "pw_teacher_viman_nagar_18_1kMtN-yN",
    "name": "Rohini Thete",
    "rawName": "rohini.thete",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1kMtN-yNuNNQe6hxZLYgyBrUh4CydK781",
    "defaultPosition": "right",
    "driveId": "1kMtN-yNuNNQe6hxZLYgyBrUh4CydK781"
  },
  {
    "id": "pw_teacher_viman_nagar_22_1Vorv3xI",
    "name": "Sabyasachi Rout",
    "rawName": "sabyasachi.rout",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1Vorv3xI7of4v3OPFA9vfZ3VMy2hZX8X0",
    "defaultPosition": "right",
    "driveId": "1Vorv3xI7of4v3OPFA9vfZ3VMy2hZX8X0"
  },
  {
    "id": "pw_teacher_tc_26_1sCewA4k",
    "name": "Saifee Khan",
    "rawName": "saifee khan",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1sCewA4kJcCJS0fkFAS2RFVxY3TyoN_X2",
    "defaultPosition": "right",
    "driveId": "1sCewA4kJcCJS0fkFAS2RFVxY3TyoN_X2"
  },
  {
    "id": "pw_teacher_tc_15_19HUNRuJ",
    "name": "Saleem Sir TC",
    "rawName": "Saleem Sir TC",
    "teacherCode": "TC",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/19HUNRuJZOCBwm7NM2IlEAfHkCQalBIls",
    "defaultPosition": "right",
    "driveId": "19HUNRuJZOCBwm7NM2IlEAfHkCQalBIls"
  },
  {
    "id": "pw_teacher_tc_23_1TZOPB9b",
    "name": "Shabbir Ahmad",
    "rawName": "Shabbir Ahmad",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1TZOPB9bzMUJBpszhr2r1q4tXo5qD5Ydf",
    "defaultPosition": "right",
    "driveId": "1TZOPB9bzMUJBpszhr2r1q4tXo5qD5Ydf"
  },
  {
    "id": "pw_teacher_viman_nagar_28_1IuWLDzI",
    "name": "Shakshi Ma'am",
    "rawName": "shakshi Ma'am",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1IuWLDzICNGLzEILPHMHvX8P1ZRKKJgZ1",
    "defaultPosition": "right",
    "driveId": "1IuWLDzICNGLzEILPHMHvX8P1ZRKKJgZ1"
  },
  {
    "id": "pw_teacher_tc_25_14gtWGJ-",
    "name": "Shivani Rai",
    "rawName": "Shivani Rai",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/14gtWGJ-lT0OoVoustmpMPVjKPkoHIYsz",
    "defaultPosition": "right",
    "driveId": "14gtWGJ-lT0OoVoustmpMPVjKPkoHIYsz"
  },
  {
    "id": "pw_teacher_tc_16_1Quvost6",
    "name": "Shraddha_khedkar",
    "rawName": "Shraddha_Khedkar_TC",
    "teacherCode": "TC",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1Quvost6nO_bw_9eSUnbGjqvaoSAQeRkq",
    "defaultPosition": "right",
    "driveId": "1Quvost6nO_bw_9eSUnbGjqvaoSAQeRkq"
  },
  {
    "id": "pw_teacher_tc_24_17ZYzC5X",
    "name": "Shreya Ma'am",
    "rawName": "Shreya Ma'am",
    "teacherCode": "",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/17ZYzC5XwNsULKganKUfOghpgG6JIgtWM",
    "defaultPosition": "right",
    "driveId": "17ZYzC5XwNsULKganKUfOghpgG6JIgtWM"
  },
  {
    "id": "pw_teacher_viman_nagar_42_16C_vgRO",
    "name": "Snehal Wadekar",
    "rawName": "Snehal Wadekar",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/16C_vgROPZoH84D-hpFdWbB9xCsemKp5J",
    "defaultPosition": "right",
    "driveId": "16C_vgROPZoH84D-hpFdWbB9xCsemKp5J"
  },
  {
    "id": "pw_teacher_viman_nagar_16_1dOHOZqH",
    "name": "Suraj Kanade",
    "rawName": "suraj.kanade",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1dOHOZqHo7vGgSoT-y2X5SSXxK8y2U6D_",
    "defaultPosition": "right",
    "driveId": "1dOHOZqHo7vGgSoT-y2X5SSXxK8y2U6D_"
  },
  {
    "id": "pw_teacher_tc_17_1NQWc89K",
    "name": "Surendra Sir TC",
    "rawName": "Surendra sir TC",
    "teacherCode": "TC",
    "subject": "General",
    "center": "TC",
    "title": "General Faculty | TC",
    "imageUrl": "https://lh3.googleusercontent.com/d/1NQWc89KsWxATzQarrtDqfLQk-qLgYcuQ",
    "defaultPosition": "right",
    "driveId": "1NQWc89KsWxATzQarrtDqfLQk-qLgYcuQ"
  },
  {
    "id": "pw_teacher_viman_nagar_29_1aoquBaW",
    "name": "Tejaswi Raj Sir",
    "rawName": "Tejaswi raj Sir",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1aoquBaWENLciOb_h3yuJ3mQihq8Myfz3",
    "defaultPosition": "right",
    "driveId": "1aoquBaWENLciOb_h3yuJ3mQihq8Myfz3"
  },
  {
    "id": "pw_teacher_viman_nagar_34_1HGjE1Nb",
    "name": "Vivek Kumar Tripathi",
    "rawName": "Vivek Kumar Tripathi",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1HGjE1Nb3h5f9Pb0oHakqZdlDtYqKsFG7",
    "defaultPosition": "right",
    "driveId": "1HGjE1Nb3h5f9Pb0oHakqZdlDtYqKsFG7"
  },
  {
    "id": "pw_teacher_viman_nagar_19_1-NEYnWB",
    "name": "Yogender Sir",
    "rawName": "Yogender Sir",
    "teacherCode": "",
    "subject": "General",
    "center": "Viman Nagar",
    "title": "General Faculty | Viman Nagar",
    "imageUrl": "https://lh3.googleusercontent.com/d/1-NEYnWBTxkJ9IrO-txEyaAiaUO3wUjTa",
    "defaultPosition": "right",
    "driveId": "1-NEYnWBTxkJ9IrO-txEyaAiaUO3wUjTa"
  }
];
